version: '3.8'

services:
  web:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
volumes:
  mongodb_data:
    driver: local
